import { useState, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ImageUpload } from "@/components/ImageUpload";
import { ScanResults } from "@/components/ScanResults";
import { HistoryPanel } from "@/components/HistoryPanel";
import { AnalyzingLoader } from "@/components/AnalyzingLoader";
import { uploadImage, analyzeScan, saveScan } from "@/lib/api";
import { toast } from "@/hooks/use-toast";
import { ScanSearch, History, FileDown, Sparkles } from "lucide-react";
import type { Scan, ScanResult } from "@/types/scan";

export default function Index() {
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<string | null>(null);
  const [result, setResult] = useState<ScanResult | null>(null);
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState("scan");
  const [historyRefresh, setHistoryRefresh] = useState(0);

  const handleImageSelected = useCallback((f: File, prev: string) => {
    setFile(f);
    setPreview(prev);
    setResult(null);
  }, []);

  const handleClear = () => {
    setFile(null);
    setPreview(null);
    setResult(null);
    setImageUrl(null);
  };

  const handleScan = async () => {
    if (!file) return;
    setLoading(true);
    setResult(null);

    try {
      const url = await uploadImage(file);
      setImageUrl(url);
      const scanResult = await analyzeScan(url);
      setResult(scanResult);
      await saveScan(url, scanResult);
      setHistoryRefresh(k => k + 1);
      toast({ title: "Analysis complete!", description: "Misconceptions identified successfully." });
    } catch (err: any) {
      toast({ title: "Analysis failed", description: err.message || "Something went wrong.", variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  const handleSelectScan = (scan: Scan) => {
    setResult(scan.result);
    setPreview(scan.image_url);
    setImageUrl(scan.image_url);
    setFile(null);
    setActiveTab("scan");
  };

  const handleExportPDF = () => {
    if (!result) return;
    // Simple print-based PDF export
    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      toast({ title: "Blocked", description: "Please allow popups to export PDF.", variant: "destructive" });
      return;
    }
    printWindow.document.write(`
      <html><head><title>Misconception Report</title>
      <style>
        body { font-family: system-ui, sans-serif; max-width: 700px; margin: 40px auto; padding: 0 20px; color: #1a1a2e; }
        h1 { color: #0891b2; font-size: 22px; }
        h2 { color: #333; font-size: 16px; margin-top: 24px; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; }
        .card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin: 10px 0; }
        .badge { display: inline-block; padding: 2px 10px; border-radius: 999px; font-size: 12px; font-weight: 600; }
        .high { background: #22c55e; color: white; }
        .medium { background: #f59e0b; color: white; }
        .low { background: #f97316; color: white; }
        .evidence { background: #f5f5f5; padding: 10px; border-radius: 6px; font-style: italic; margin-top: 8px; }
        .script { background: #ecfdf5; border: 1px solid #6ee7b7; padding: 16px; border-radius: 8px; margin-top: 16px; }
        .footer { margin-top: 40px; text-align: center; color: #9ca3af; font-size: 12px; }
      </style></head><body>
      <h1>🔍 Misconception Scanner Report</h1>
      <h2>Problem</h2><p>${result.problem}</p>
      <h2>Student's Working</h2><p>${result.student_steps}</p>
      <h2>Root Misconceptions</h2>
      ${result.misconceptions.map(m => `
        <div class="card">
          <strong>${m.name}</strong>
          <span class="badge ${m.confidence > 80 ? 'high' : m.confidence >= 70 ? 'medium' : 'low'}">${m.confidence}%</span>
          <p>${m.description}</p>
          <div class="evidence">"${m.evidence}"</div>
        </div>
      `).join("")}
      <h2>Interventions</h2>
      <div class="card"><strong>Analogy:</strong> ${result.interventions.analogy}</div>
      <div class="card"><strong>Visual Idea:</strong> ${result.interventions.visual_idea}</div>
      <div class="card"><strong>Follow-up Questions:</strong><ol>${result.interventions.follow_up_questions.map(q => `<li>${q}</li>`).join("")}</ol></div>
      <h2>Parent Script</h2>
      <div class="script">${result.parent_script}</div>
      <div class="footer">Generated by Misconception Scanner · ${new Date().toLocaleDateString("en-IN")}</div>
      </body></html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b bg-card/80 backdrop-blur-sm sticky top-0 z-10">
        <div className="container max-w-3xl mx-auto px-4 h-14 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <ScanSearch className="h-6 w-6 text-primary" />
            <span className="font-heading font-bold text-lg text-foreground">Misconception Scanner</span>
          </div>
          {result && (
            <Button variant="outline" size="sm" onClick={handleExportPDF}>
              <FileDown className="h-4 w-4 mr-1.5" /> Export PDF
            </Button>
          )}
        </div>
      </header>

      <main className="container max-w-3xl mx-auto px-4 py-6">
        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList className="w-full mb-6">
            <TabsTrigger value="scan" className="flex-1 gap-1.5">
              <ScanSearch className="h-4 w-4" /> Scan
            </TabsTrigger>
            <TabsTrigger value="history" className="flex-1 gap-1.5">
              <History className="h-4 w-4" /> History
            </TabsTrigger>
          </TabsList>

          <TabsContent value="scan" className="space-y-5">
            {/* Hero text */}
            {!preview && !result && (
              <div className="text-center mb-2">
                <h1 className="text-2xl sm:text-3xl font-heading font-extrabold text-foreground leading-tight">
                  Scan Student Work →<br />
                  <span className="text-primary">Find Root Misconceptions</span> Instantly
                </h1>
                <p className="mt-3 text-muted-foreground max-w-md mx-auto">
                  Upload a photo of any math worksheet. Our AI diagnoses deep conceptual gaps — not just surface errors.
                </p>
              </div>
            )}

            <ImageUpload
              onImageSelected={handleImageSelected}
              preview={preview}
              onClear={handleClear}
              disabled={loading}
            />

            {/* Scan button */}
            {preview && !result && !loading && (
              <Button
                onClick={handleScan}
                className="w-full h-12 text-base font-semibold"
                disabled={!file && !imageUrl}
              >
                <Sparkles className="h-5 w-5 mr-2" />
                Scan with AI
              </Button>
            )}

            {loading && <AnalyzingLoader />}

            {result && <ScanResults result={result} />}
          </TabsContent>

          <TabsContent value="history">
            <HistoryPanel onSelectScan={handleSelectScan} refreshKey={historyRefresh} />
          </TabsContent>
        </Tabs>
      </main>

      {/* Footer */}
      <footer className="border-t mt-12 py-6">
        <p className="text-center text-xs text-muted-foreground">
          Built as AI Builder portfolio project for Cuemath role
        </p>
      </footer>
    </div>
  );
}
